GET http://localhost:3333/courses?orderBy=title

###

GET http://localhost:3333/courses/c500db14-5c92-4767-8608-335769780f76
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI3N2UwMDFhYS0wNzJmLTQ1YzItOTQyNi1iNzY1MTNmZTk4OWUiLCJyb2xlIjoibWFuYWdlciIsImlhdCI6MTc1NTYxNjIzOH0.YoHjHaGRELu1Wxgs48U7c-nbEThuWgv3TWWD9L0kR9o

###

POST http://localhost:3333/courses
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI3N2UwMDFhYS0wNzJmLTQ1YzItOTQyNi1iNzY1MTNmZTk4OWUiLCJyb2xlIjoibWFuYWdlciIsImlhdCI6MTc1NTYxNjIzOH0.YoHjHaGRELu1Wxgs48U7c-nbEThuWgv3TWWD9L0kR9o

{
  "title": "Curso de Cobol"
}

###

POST http://localhost:3333/sessions
Content-Type: application/json

{
  "email": "Warley58@gmail.com",
  "password": "123456"
}